[project]
name = "ibm-ai-engineering"
version = "0.1.0"
description = "Coursera IBM AI Engineering Professional Certificate"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "matplotlib==3.9.3",
    "notebook>=7.5.0",
    "numpy==2.2.0",
    "pandas==2.2.3",
    "scikit-learn==1.6.0",
]
